import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Image from 'next/image'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='min-h-screen'>
          <header className='h-16 w-full bg-[#ff6300] flex justify-between px-4'>
            <Image
              src={'/autoworld-logo.jpg'}
              alt='logo'
              width={100}
              height={100}
              unoptimized
              className='bg-blend-multiply object-cover'
            />
            <ul className='flex h-full items-center justify-evenly gap-4 text-white text-xl font-semibold flex-1'>
              <li>รู้จักเรา</li>
              <li>ผลิตภัณฑ์</li>
              <li>สื่อประชาสัมพันธ์</li>
              <li>ติดต่อ</li>
            </ul>
          </header>
          {children}
        </div>
      </body>
    </html>
  )
}
